### ISSUE TITLE
有办法自动判断是否有声音不？

### ISSUE THREAD

**Issue by terry8204** [xqq/mpegts.js#10]
大佬，hasAudio能自动不？有的设备指定有声音，实际推送的时候，可能又没声音上来，这样就导致播放器播放不了视频。
很头疼的问题。希望大佬，能解决下这个千年问题，以前flv.js 也是需要指定。

**Comment by FredZeng** [comment]
是不是给 mediaSource 指定了 `hasAudio: true`？是的话，删掉就好；不是的话可以详细描述一下你的场景吗？

**Comment by xqq** [comment]
`onMetaData` 里面是有 `hasAudio` / `hasVideo` 指定的，确保其准确符合实际情况即可

**Comment by terry8204** [comment]
实际应用的时候，我也不知道设备是否带了声音留，有的不带，有的带，如果没带，初始化player的时候没匹配，就播放不了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月19日(周六) 上午8:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xqq/mpegts.js] 有办法自动判断是否有声音不？ (#10)




 
onMetaData 里面是有 hasAudio / hasVideo 指定的，确保其准确符合实际情况即可

**Comment by xqq** [comment]
确保 onMetaData 里面的 hasAudio / hasVideo 是准确的，客户端不指定则一般没有问题

**Comment by ljia310** [comment]
macos safari,播放没有音频的视频，初始化player的时候（hasAudio :false)，也播放不了，需要手工点击开始才能播放。
![image](https://user-images.githubusercontent.com/3294399/124205846-b2c4c180-db14-11eb-96ff-70434dd5666c.png)

**Comment by FredZeng** [comment]
> macos safari,播放没有音频的视频，初始化player的时候（hasAudio :false)，也播放不了，需要手工点击开始才能播放。
> ![image](https://user-images.githubusercontent.com/3294399/124205846-b2c4c180-db14-11eb-96ff-70434dd5666c.png)

我觉得你可能是想要自动播放，你需要在 <video> 上加上 muted 属性，`<video autoplay muted></video>`

**Comment by ljia310** [comment]
> > macos safari,播放没有音频的视频，初始化player的时候（hasAudio :false)，也播放不了，需要手工点击开始才能播放。
> > ![image](https://user-images.githubusercontent.com/3294399/124205846-b2c4c180-db14-11eb-96ff-70434dd5666c.png)
> 
> 我觉得你可能是想要自动播放，你需要在 `<video>` 上加上 muted 属性，`<video autoplay muted></video>`

的确是需要自动播放功能，已经加了自动播放属性<video autoplay muted></video>，没有作用。
带音频的就正常，不带音频的就需要手工点击开始才能播放，所以感觉还是和音频有关

**Comment by FredZeng** [comment]
> > > macos safari,播放没有音频的视频，初始化player的时候（hasAudio :false)，也播放不了，需要手工点击开始才能播放。
> > > ![image](https://user-images.githubusercontent.com/3294399/124205846-b2c4c180-db14-11eb-96ff-70434dd5666c.png)
> > 
> > 
> > 我觉得你可能是想要自动播放，你需要在 `<video>` 上加上 muted 属性，`<video autoplay muted></video>`
> 
> 的确是需要自动播放功能，已经加了自动播放属性，没有作用。
> 带音频的就正常，不带音频的就需要手工点击开始才能播放，所以感觉还是和音频有关

能把视频传上来看看吗？

**Comment by xqq** [comment]
能否自动播放是浏览器的限制

**Comment by ljia310** [comment]
> > > > macos safari,播放没有音频的视频，初始化player的时候（hasAudio :false)，也播放不了，需要手工点击开始才能播放。
> > > > ![image](https://user-images.githubusercontent.com/3294399/124205846-b2c4c180-db14-11eb-96ff-70434dd5666c.png)
> > > 
> > > 
> > > 我觉得你可能是想要自动播放，你需要在 `<video>` 上加上 muted 属性，`<video autoplay muted></video>`
> > 
> > 
> > 的确是需要自动播放功能，已经加了自动播放属性，没有作用。
> > 带音频的就正常，不带音频的就需要手工点击开始才能播放，所以感觉还是和音频有关
> 
> 能把视频传上来看看吗？
临时测试地址： 局域网内的摄像头
https://yun.saftop.cn/live?app=live&stream=test

**Comment by ljia310** [comment]
> 能否自动播放是浏览器的限制

macos safari,带音频的自动播放就正常，不带音频的就需要手工点击开始才能播放。
chrom浏览器正常。

**Comment by ljia310** [comment]
> > > > macos safari,播放没有音频的视频，初始化player的时候（hasAudio :false)，也播放不了，需要手工点击开始才能播放。
> > > > ![image](https://user-images.githubusercontent.com/3294399/124205846-b2c4c180-db14-11eb-96ff-70434dd5666c.png)
> > > 
> > > 
> > > 我觉得你可能是想要自动播放，你需要在 `<video>` 上加上 muted 属性，`<video autoplay muted></video>`
> > 
> > 
> > 的确是需要自动播放功能，已经加了自动播放属性，没有作用。
> > 带音频的就正常，不带音频的就需要手工点击开始才能播放，所以感觉还是和音频有关
> 
> 能把视频传上来看看吗？

临时测试地址：
http-flv
http://14.29.214.79/live?app=live&stream=test

**Comment by terry8204** [comment]
目前这个我改成了，视频和声音分开推流，解决了这个问题，但会导致不同步。
