### ISSUE TITLE
内存泄漏警告

### ISSUE THREAD

**Issue by Greasen** [xqq/mpegts.js#112]
16路画面播放的时候浏览器抛出：MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit，内存泄漏的警告

**Comment by Warehouse-Model** [comment]
问题解决了吗

**Comment by xqq** [comment]
It could be ignored AFAIK

**Comment by Greasen** [comment]
> It could be ignored AFAIK

ok，thankyou
