### ISSUE TITLE
播放flv视频，可能会引发内存泄露

### ISSUE THREAD

**Issue by 823639792** [xqq/mpegts.js#139]
两种情况
1、如果直播视频不包含音频（监控视频比较常见），chrome将标签页切换到后台时，会将视频暂停，而这时视频依旧不断追加到缓存中
  设置autoCleanupMaxBackwardDuration无效，因为视频被暂停了，buffered.start(0) 一直没有增加
 可以通过不断设置element.currentTime进行规避，但感觉不太好

2、player._msectl._idrList._list  会一直增加，没有找到自动清空的位置

**Comment by xqq** [comment]
> 2、player._msectl._idrList._list 会一直增加，没有找到自动清空的位置

I'm fixing this problem on another branch https://github.com/xqq/mpegts.js/commit/0d523fac41d4607531788f1ea4c4448d92d39295 .You can build by yourself or wait it to be merged into master.

**Comment by xqq** [comment]
@823639792 
Fixed in master branch.
