### ISSUE TITLE
使用 customLoader 自定义loader，在播放器实例上未获取到相关方法

### ISSUE THREAD

**Issue by Greasen** [xqq/mpegts.js#143]
绑定了 customLoader ，但是在实例上未获取到; 在其中 open 方法中获取到 websocket 实例，但是在外部文件中无法读取，从而无法获取到 websocket 实例，以及无法获取到自定义 loader 上的方法。作者在 flvjs 中提到： “自己把字节流拆出来之后，用 customLoader 的形式自己实现一个 loader 把字节流提供给 flv.js，继承 flvjs.BaseLoader”。在mpegts.js 中源码中 "new this._loaderClass(this._seekHandler, this._config);"，所以在外部无法在重新new 一个实例

**Comment by Greasen** [comment]
作者是不是通过在播放器实例上暴露自定义的loader项给用户可以使用 customLoader 中的方法呢？而不是在config 上绑定的 customLoader

**Comment by Stefanxx** [comment]
> 作者是不是通过在播放器实例上暴露自定义的loader项给用户可以使用 customLoader 中的方法呢？而不是在config 上绑定的 customLoader

你的问题解决了吗
