### ISSUE TITLE
h265 是不是需要有高一点的cpu啊

### ISSUE THREAD

**Issue by Yorlg** [xqq/mpegts.js#148]
设备没有显卡，播放H265带音频就只显示音频条不显示视频画面，用的是谷歌浏览器 @xqq

**Comment by xqq** [comment]
Required hardware decoder

**Comment by Yorlg** [comment]
> Require hardware decoder

不好意思我发错了issues，我在一个小的设备上，没有显卡只有核显 播放h265的时候只显示音频不显示视频，在提了issues之后才进行的测试，才发现没有显卡导致的。
