### ISSUE TITLE
something wrong with getting hevc unitType

### ISSUE THREAD

**Issue by FredZeng** [xqq/mpegts.js#159]
https://github.com/xqq/mpegts.js/blob/ee19138ab89af9629f1bbb13c44929b779296d24/src/demux/flv-demuxer.js#L1464

When I play hevc over flv, I got wrong unitType. 
According to hevc specification, NAL unit header syntax should be:
![image](https://github.com/xqq/mpegts.js/assets/17154608/e6e21ffa-c943-4c3b-ad8d-1f5b65d14293)

A better way to get nal_unit_type should be:
```js
let unitType = (v.getUint8(offset + lengthSize) & 0x7E) >> 1;
```

**Comment by xqq** [comment]
Thanks for your report! This will be fixed in #160
