### ISSUE TITLE
Correct playback of .m2ts file

### ISSUE THREAD

**Issue by superfashi** [xqq/mpegts.js#2]
Here is a normal BDAV (.m2ts) file that contains one stream of H.264 and one stream of PCM. I understand that PCM is not supported, yet the video is displayed incorrectly as well.

https://drive.google.com/file/d/1ge5jDCBRR98nPsKEF6AzGgUMFlZ5gNIL/view?usp=sharing

Please take a look.

**Comment by xqq** [comment]
Looks good here
![image](https://user-images.githubusercontent.com/4645762/116512444-05121800-a903-11eb-8623-4e89388c1d07.png)

**Comment by superfashi** [comment]
huh okay, it does not seem to work on my side. Tried with Microsoft Edge
Version 90.0.818.46 and Google Chrome Version 90.0.4430.93. Any debug info you need?

**Comment by xqq** [comment]
ghpages didn't update, yet

**Comment by xqq** [comment]
ghpages updated

**Comment by superfashi** [comment]
awesome
