### ISSUE TITLE
使用mpegts.js 进行ws视频流的历史回放，控制 video的playbackRate实现倍速切换无效

### ISSUE THREAD

**Issue by SnowBeatRain** [xqq/mpegts.js#206]
使用flvjs 可以，使用mpegts不行
![image](https://github.com/user-attachments/assets/8f9e02ea-1934-4094-acbd-70dfc906e057)

**Comment by SnowBeatRain** [comment]
关闭追帧即可

**Comment by jiu-hao** [comment]
enableStashBuffer 是这个参数吗设置为false 但是正常播放的时候需要呢？

> 关闭追帧即可
