### ISSUE TITLE
当播放多个flv档案的时候,seek segment 会失败

### ISSUE THREAD

**Issue by ideaparker** [xqq/mpegts.js#25]
当播放多个影片的时候,如果都不要seek 是可以正常播完 ,
有个情境是 ,如果一开始播放的时候 ,就seek 选取最后的segment ,此时还是可以正常播放
但如果在这时候选取一开始的segment 会直接loop 卡住不播放
附近有我的图档 还有档案  ,之后再跳回第一个位置

![document1](https://user-images.githubusercontent.com/17937672/133006040-3db9b2b5-5a2a-4d15-870e-889f3d6202c7.png)

我是直接seek 在最后一个segment ,1200这个位置,此时还是正常播放
![document2](https://user-images.githubusercontent.com/17937672/133006102-c6a23a77-6298-48c3-b857-fbafbff82594.png)

seek 回 第一个segment ,loop 直接卡死
![document3](https://user-images.githubusercontent.com/17937672/133006028-c744dfb4-3bbe-4489-8f86-7d3307695ee1.png)

json file
{
    "type": "flv",
    "duration": 1418440,
    "segments": [
        {
            "duration": 312640,
            "filesize": 20676652,
            "url": "http://127.0.0.1:8081/demo/file/xxx-1tx411k7PX_part1.flv"
        },{
            "duration": 354480,
            "filesize": 26951956,
            "url": "http://127.0.0.1:8081/demo/file/xxx-1tx411k7PX_part2.flv"
        },{
            "duration": 407240,
            "filesize": 25339028,
            "url": "http://127.0.0.1:8081/demo/file/xxx-1tx411k7PX_part3.flv"
        },{
            "duration": 344080,
            "filesize": 15874198,
            "url": "http://127.0.0.1:8081/demo/file/xxx-1tx411k7PX_part4.flv"
        }
    ]
}

**Comment by xqq** [comment]
应该是 58792a08fdfa7e212630ddb72d3f4bc696e8cbfb 这个 commit 导致的

**Comment by xqq** [comment]
已回滚修复，感谢反馈
https://github.com/xqq/mpegts.js/releases/tag/v1.6.8

**Comment by ideaparker** [comment]
OK
