### ISSUE TITLE
FLV with HEVC support?

### ISSUE THREAD

**Issue by n3g2** [xqq/mpegts.js#64]
Chrome 105 supports 265 decoding. Is there any plan for flv 265?

**Comment by xqq** [comment]
Yes

**Comment by winlinvip** [comment]
Great work! SRS 6.0 is working for 265 live streaming, for h.265 over HTTP-TS, HTTP-FLV and HLS. And SRS has always been using H5 player from xqq, really appreciate about your awesome and hard work.
