### ISSUE TITLE
Build process throws ts errors for express-serve-static-core

### ISSUE THREAD

**Issue by dbussert** [xqq/mpegts.js#69]
```
npm install
npm run build
```

results in many of these errors 

![image](https://user-images.githubusercontent.com/2479487/198050806-d22438b2-5dc3-4bc1-90e1-57444d25b393.png)

It looks to be the same issue discussed here https://github.com/DefinitelyTyped/DefinitelyTyped/issues/62300. `@types/express-serve-static-core` 4.17.31 version caused the breaking change a month ago. A work around is to force the previous version of the library in `devDependencies`

```
"@types/express-serve-static-core": "4.17.30",
```

**Comment by dbussert** [comment]
The root cause appears to be `@types/express-serve-static-core` broke backwards compatibility with typescript 3.x. A more permanent fix could be to move to 4.x

**Comment by xqq** [comment]
Try d5000368a420a23df4a4693509c8cfd3ecf26f35

**Comment by dbussert** [comment]
that worked
