### ISSUE TITLE
MP2 Audio support

### ISSUE THREAD

**Issue by andreadaoud** [xqq/mpegts.js#78]
Hi, is it possible to support MP2 audio? I'm willing to provide a source with MP2 audio for devs to test (but unfortunately I'm cannot post it in public).

**Comment by xqq** [comment]
Ya I think the Media Source Extensions doesn't support MP2 codec

**Comment by andreadaoud** [comment]
Is it possible that we play this through some kind of magic, e.g. use wasm to software-ly decode it?

**Comment by xqq** [comment]
Yes, it's possible by using WebAssembly and WebAudio.

**Comment by andreadaoud** [comment]
It seems that now mpegts.js supports the audio format with the MP3 update. Thank you for your hard work!
