### ISSUE TITLE
h265 直播延时

### ISSUE THREAD

**Issue by hkc452** [xqq/mpegts.js#94]
随着直播时间延长，延时越来越大

**Comment by lizhuozhen** [comment]
试试追帧，以下是我在项目封装的追帧函数，仅供参考
delayHandler () {
      const p = this.player
      if (!p || !p.buffered || !p.buffered.length) {
        return
      }
      const diff = p.buffered.end(0) - p.currentTime // 计算最新推流的时间和现在播放器播放推流的时间
      if (diff < 0.8) {
        if (p.playbackRate !== 1) {
          p.playbackRate = 1 // 恢复原速
        }
      } else {
        p.currentTime = p.buffered.end(0) - 0.2
        p.playbackRate = 1.1
      }
   }

**Comment by xcchcaptain** [comment]
> 试试追帧，以下是我在项目封装的追帧函数，仅供参考 delayHandler () { const p = this.player if (!p || !p.buffered || !p.buffered.length) { return } const diff = p.buffered.end(0) - p.currentTime // 计算最新推流的时间和现在播放器播放推流的时间 if (diff < 0.8) { if (p.playbackRate !== 1) { p.playbackRate = 1 // 恢复原速 } } else { p.currentTime = p.buffered.end(0) - 0.2 p.playbackRate = 1.1 } }
这个方法在什么时机调用呢
